# Generated by Django 4.2.15 on 2025-01-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0537_data_color_themes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmObjectType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="propertydefinition",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "event"), (2, "person"), (3, "group"), (4, "session"), (5, "object")], default=1
            ),
        ),
        migrations.CreateModel(
            name="CrmObject",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("properties", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "object_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.crmobjecttype"),
                ),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.team")),
            ],
        ),
        migrations.AddField(
            model_name="propertydefinition",
            name="object_type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="posthog.crmobjecttype"
            ),
        ),
    ]
